config/routes.rb
SuperAdmin::Application.routes.draw do
  

  devise_for :users, path: "/", path_names: { 
    sign_in:        'login', 
    sign_out:       'logout', 
    password:       'secret', 
    confirmation:   'verification', 
    unlock:         'unblock', 
    registration:   'register', 
    sign_up:        '' 
  }
  resources :users
  root 'page#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  before_action :authenticate_user!

	def index
		# this is going to be fucking awesome
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # before_action :check_for_super_admin
  # before_action :authenticate_admin!
  # before_filter do 
  #   redirect_to :new_user_session_path unless current_user && current_user.admin?
  # end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :group)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(level)
		case level
			when :notice then "alert alert-info animated fadeIn"
			when :success then "alert alert-success animated fadeIn"
			when :error then "alert alert-danger animated fadeIn"
			when :warning then "alert alert-warning animated fadeIn"
			else "alert alert-warning animated fadeIn"
		end
	end

	def sidebar_link name, path 
		if current_page?(path)
			return "<li class='active'><a href='#{path}'>#{name}</a></li>".html_safe
		else
			return "<li><a href='#{path}'>#{name}</a></li>".html_safe
		end
	end

end

app/helpers/devise_helper.rb
module DeviseHelper

  # Override devise error html
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation" class="alert alert-danger animated fadeIn">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperAdmin</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="<%= image_path 'favicon.ico' %>">
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<% 
		logged_out_id = 'login'
		if current_user
			logged_out_id = ''
		end
	%>
	<% if current_user %>	      

	    <div id="sidebar">
			<ul>      	
				<li><%= link_to 'Dashboard', root_path %></li>
				<%= sidebar_link 'Users', users_path %>
				<li><%= link_to 'Log out', destroy_user_session_path, method: 'delete' %></li>
			</ul>
	    </div>
	
	<% end %>

    <div id="<%= logged_out_id %>" class="main">
		<%= render 'partials/flash_messages' %>
		<%= yield %>
    </div> <!-- end main -->
	


  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/page/index.html.erb
<h1>index.html.erb</h1>


<% if current_user %>

	<h3>User Model</h3>
	<ul>
		
	<li>Current user: <%= current_user.email %></li>
	<li>Sign in count: <%=current_user.sign_in_count %></li>
	<li>Date created: <%= current_user.created_at.to_formatted_s(:long_ordinal) %></li>
	<li>User Session: <%= user_session %></li>
	<% current_user.attributes.each do | k,v | %>
		<li><strong><%= k %>:&nbsp;&nbsp;</strong><%= v %></li>
	<% end %>

	</ul>

<% end %>

app/views/partials/_custom_login_form.erb
<div id="login">
	<%= form_for(:user, :url => session_path(:user)) do |f| %>
		<div class="field">
			<%= f.text_field :email, :placeholder => 'Username' %>
			<%= f.password_field :password, :placeholder => '********' %>
		</div>
		<div class="field">	
			<%= f.check_box :remember_me %>
			<%= f.label :remember_me %>
		</div>
		<div class="field">
			<%= f.submit 'Sign in' %>
		</div>
		<%= link_to "Forgot your password?", new_password_path(:user) %>
	<% end %>
</div>

app/views/partials/_flash_messages.html.erb
<% flash.each do |key, value| %>
	<div class="<%= flash_class(key) %> fade in">
		<%= value %>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
    
    <div class="form-group"><%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %></div>

    <div class="form-group"><%= f.label :password %><br />
      <%= f.password_field :password, autocomplete: "off" %></div>

    <div class="form-group"><%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Admin</th>
      <th>Current sign in at</th>
      <th>Last sign in IP</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user!</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>